### ISSUE TITLE
[BUG] SynchronizationManager.seedDBFromJSONFiles throwing incorrect invalidFilePath

### ISSUE THREAD

**Issue by Basca** [contentful/contentful-persistence.swift#100]
### persistence-sdk information
  * version: 0.16.1

### Describe the bug
SynchronizationManager.seedDBFromJSONFiles throws incorrect invalidFilePath while providing correct folder name and bundle.

example: 
`try syncManager.seedDBFromJSONFiles(in: "ContentfulSeed", in: Bundle.main)` (ContentfulSeed is a correct folder reference and added to the bundle) 

results in:
`DatabaseSeedingError.invalidFilePath`

#### Debug logs
While debugging I can tell the filePaths are correct, however the localesJSONFilePath and firstFilePath are empty, causing the above error.

Example simulator log:
`
"filesPaths:" [
"/Users/bas/Library/Developer/CoreSimulator/Devices/<redacted>/data/Containers/Bundle/Application/<redacted>/<redacted>.app/ContentfulSeed/locales.json",
"/Users/bas/Library/Developer/CoreSimulator/Devices/<redacted>/data/Containers/Bundle/Application/<redacted>/<redacted>.app/ContentfulSeed/10.json",
...
"/Users/bas/Library/Developer/CoreSimulator/Devices/<redacted>/data/Containers/Bundle/Application/<redacted>/<redacted>.app/ContentfulSeed/23.json"
]
"localesJSONFilePath:" nil
"firstFilePath:" nil
`

Example device log:
`
"filesPaths:" [
"/private/var/containers/Bundle/Application/<redacted>/<redacted>.app/ContentfulSeed/19.json"
]
"localesJSONFilePath:" nil
"firstFilePath:" nil
`

#### Possible fix
When changing inside: [file](https://github.com/contentful/contentful-persistence.swift/blob/master/Sources/ContentfulPersistence/SynchronizationManager%2BSeedDB.swift)
The occurrences of:
`URL(string: $0)?`
with
`URL(fileURLWithPath: $0)`

The synchronisation succeeds.

**Comment by mariuskatcontentful** [comment]
Closing as the PR has been merged with the fix.
