### ISSUE TITLE
[BUG] Incremental sync issues with 0.17.1

### ISSUE THREAD

**Issue by Kevinvandenhoek** [contentful/contentful-persistence.swift#105]
Hi,

After updating to the 0.17.1 SDK, I noticed that incremental syncing seems to have broken. What happens is the following:
- I do a clean sync from scratch, everything is all good.
- I update some content in our Contentful space, like for example lets say we have a 'Person' object and there is a name on it, I change the name from 'Paul' to 'Jacob'
- I restart the app to perform the incremental sync to make sure the CoreData database is up to date again, now there are suddenly two person objects, both the old one and the new one, respectively 'Paul' and 'Jacob', where I would expect there to only be 'Jacob'.

This obviously causes a variety of issues. I did some more research and found out the last version where incremental syncs still seemed to work is 0.16.1. When I do some logging, I can see there are no 'create' calls occurring during this incremental sync, only fetches (and saves). When I log with 0.17.1 I suddenly see a batch of 'create' calls occurring for the 'Person' objects (presumably the updated version with the new 'Jacob' name), but no 'delete' calls, indicating that indeed, new entities are created for the updated entries, but the old outdated entries are never deleted, thus ending up with an 'entity leak'.

**Comment by tomkowz** [comment]
I did take a quick look at that. Here is how I tried to reproduce the issue with 0.17.1.

1. Create a type with "title" property.
2. Create one instance of that model in the Contentful.com
3. Sync that type in the app.
4. Fetch all instances of that type; See there is 1 instance.
5. Close app.
6. Change "title" on Contentful to be different than it is now and publish changes.
7. Launch the app again and perform sync; See three is still 1 instance with updated title.

Is that reflecting your scenario?

**Comment by Kevinvandenhoek** [comment]
> @Kevinvandenhoek
> 
> I did take a quick look at that. Here is how I tried to reproduce the issue with 0.17.1.
> 
> 1. Create a type with "title" property.
> 2. Create one instance of that model in the Contentful.com
> 3. Sync that type in the app.
> 4. Fetch all instances of that type; See there is 1 instance.
> 5. Close app.
> 6. Change "title" on Contentful to be different than it is now and publish changes.
> 7. Launch the app again and perform sync; See three is still 1 instance with updated title.
> 
> Is that reflecting your scenario?

Hi there,

Yes, this is my scenario. Our project is quite big and complex, so I will try to create a separate test project to see if I get the same results as you, thanks for checking!

**Comment by Kevinvandenhoek** [comment]
Due to current time constraints I have which don't allow me to properly create a separate test project to properly give a reproducible result, I will close the issue for now. I will most likely come back to it in about 2 weeks :)

**Comment by tomkowz** [comment]
@Kevinvandenhoek I did take a look again on the changes I made in 0.17.1 and indeed there might be a case when entry is created instead of being updated. Let me create a PR, and the Fix should be merged and released over the weekend.

**Comment by Kevinvandenhoek** [comment]
> @Kevinvandenhoek I did take a look again on the changes I made in 0.17.1 and indeed there might be a case when entry is created instead of being updated. Let me create a PR, and the Fix should be merged and released over the weekend.

Thats great news! thanks very much! :)
