### ISSUE TITLE
I cannot resolve one to many relationship.

### ISSUE THREAD

**Issue by edward121** [contentful/contentful-persistence.swift#11]
![screen shot 2017-03-06 at 16 35 10](https://cloud.githubusercontent.com/assets/22666011/23616762/1a0e4e40-028b-11e7-8abe-5c11fc0fa1f3.png)
![screen shot 2017-03-06 at 16 35 22](https://cloud.githubusercontent.com/assets/22666011/23616764/1a164eba-028b-11e7-9e94-382294cd275a.png)
![screen shot 2017-03-06 at 16 35 39](https://cloud.githubusercontent.com/assets/22666011/23616763/1a0e3bee-028b-11e7-83ed-cbb1faa53c5a.png)
![screen shot 2017-03-06 at 16 38 10](https://cloud.githubusercontent.com/assets/22666011/23616897/87e90b6c-028b-11e7-8100-b4a5a65ba1fb.png)
![screen shot 2017-03-06 at 16 39 15](https://cloud.githubusercontent.com/assets/22666011/23616900/889a1588-028b-11e7-840d-e60bd818c8a1.png)
![screen shot 2017-03-06 at 16 39 26](https://cloud.githubusercontent.com/assets/22666011/23616899/8896380a-028b-11e7-9616-7a8a7dbf3eb2.png)

![screen shot 2017-03-06 at 16 41 10](https://cloud.githubusercontent.com/assets/22666011/23617001/d4b15daa-028b-11e7-927a-d08c85e36569.png)
What's wrong in my solution?

**Comment by loudmouth** [comment]
Hey @edward121 this is less of a question about the SDK and more of a question about how to use CoreData. I recommend making sure to double check, via a Google search, the debug console output when running into similar issues in the future before opening a Github issue.

In this case, you are specifying an `NSSet` on your `appearances` property when the CoreData model is returning an `NSOrderedSet`. To fix this, select the `appearances` relationship on your CoreData model and open the assistant editor on the right. Now toggle the box that says "Arrangement" > "Ordered". See the photo below:

<img width="947" alt="screen shot 2017-03-07 at 10 23 03" src="https://cloud.githubusercontent.com/assets/4554909/23649833/31c1d2e2-0320-11e7-9c11-404a99bcd816.png">
