### ISSUE TITLE
Updates and releases needed

### ISSUE THREAD

**Issue by sebastianludwig** [contentful/contentful-persistence.swift#20]
The latest release of `contentful-persistence` is `0.3.0` from 4 month ago and it lists `'Contentful', '~> 0.3.1'` as dependency (also 4 month old). Since then Contentful has been released multiple times, currently at version `0.6`. The current master references Contentful `0.4.1` (only three weeks old) which unfortunately has some [bugs](https://github.com/contentful/contentful.swift/issues/68).

The awesome advancements in one repository are pretty useless if other project dependencies are tied to old releases :-(

Do you have a timeline or roadmap when we can expect a synced set of up-to-date releases?

**Comment by loudmouth** [comment]
There was some additional work that ended up on my plate last week so my work on contentful-persistence.swift was delayed unfortunately.

I'm working on the persistence library this week and hope to have a compatibility update released by early next week; earlier if possible. I'll also work on making it easier to contribute to remedy #19 as well.

Thanks for your patience.

**Comment by loudmouth** [comment]
@sebastianludwig , I've just pushed a branch `improvement/contentful-0.6.0` to this repo which updates the dependency on `contentful.swift` to `~> 0.6.1`.

Though there is some more work to be done before publishing, all currently implemented tests for this repo are passing, so feel free to give it a try.

**Comment by loudmouth** [comment]
@sebastianludwig just wanted to give you a quick update: I've been working on compatibility branches for both contentful.swift and contentful-persistence.swift. Both branches have not been pushed to remote origin yet. I don't think it will be ready for publishing until Wednesday June 21 at latest.
