### ISSUE TITLE
Use of try! should be avoided

### ISSUE THREAD

**Issue by tapwork** [contentful/contentful-persistence.swift#25]
During my Unit Tests I had some crashes that are caused by an error during CoreData save
```
public func save() {
        try! persistentStore.save()
    }
```
I saw plenty of places in the `SynchronizationManager` where error handling is ignored / disabled by the usage of `try!`.
Why don't you properly use `do-catch` or just `try?`. 
But `try!` should only be used if you're certain that there is no error thrown

See: https://github.com/contentful/contentful-persistence.swift/pull/26

**Comment by loudmouth** [comment]
Fixed in #26
