### ISSUE TITLE
How to create Realm Persistence Store?

### ISSUE THREAD

**Issue by Naresh16591** [contentful/contentful-persistence.swift#3]

**Comment by neonichu** [comment]
There is no implementation of a Realm persistence store at the moment. It should be relatively straightforward to create one on your own, though, the Core Data one is less than 150 lines of code: <https://github.com/contentful/contentful-persistence.swift/blob/master/Code/CoreDataStore.swift>

**Comment by Naresh16591** [comment]
`import Foundation
import RealmSwift
import ContentfulPersistence

class RealmPersistanceStore: PersistenceStore {

    private var realm: Realm

    init(realm: Realm) {

        self.realm = realm
    }

    func create<T>(type: Any.Type) throws -> T {

        if let c = type as? AnyClass {
            if let o = c as? Object.Type {
                let object = o.init()
                print(object)
                if let t = object as? T {
                    return t
                }
            }

        }
        throw Errors.InvalidType(type: type)
    }

    func fetchAll<T>(type: Any.Type, predicate: NSPredicate) throws -> [T] {
        if let c = type as? AnyClass {
            if let o = c as? Object.Type {
                let objects = realm.objects(o).filter(predicate)
                var array: [T] = []
                for i in objects {
                    if let o = i as? T {
                        array.append(o)
                    }
                }
                return array
            }
        }
        throw Errors.InvalidType(type: type)

    }

    func propertiesFor(type type: Any.Type) throws -> [String] {
        if let c = type as? AnyClass {
            if let o = c as? Object.Type {
                let properties = o.init().objectSchema.properties
                return try properties.map { $0.description }.filter {
                    try relationshipsFor(type: type).contains($0)
                }
            }
        }

        throw Errors.InvalidType(type: type)
    }
    func delete(type: Any.Type, predicate: NSPredicate) throws {
        let objects: [Object] = try fetchAll(type, predicate: predicate)
        objects.forEach {
            self.realm.delete($0)
        }
    }

    func relationshipsFor(type type: Any.Type) throws -> [String] {
        if let c = type as? AnyClass {
            if let o = c as? Object.Type {
                let relationShips = o.init().objectSchema.properties.filter {
                    let objectRelationShips = $0.type == PropertyType.Object
                    let linkedObjectRelationShips = $0.type == PropertyType.LinkingObjects
                    return objectRelationShips || linkedObjectRelationShips
                }.map {
                    $0.description
                }
                return relationShips
            }
        }
        throw Errors.InvalidType(type: type)
    }

    func save() throws {

    }

}` 

It throws me an error OfflinePersistance[25301:6886769] Error: ContentfulError(sys: ["id": BadRequest, "type": Error], identifier: "BadRequest", type: "Error", message: "The sync token you sent was invalid. Consider trying an initial sync by passing \"initial=true\".", requestId: "58b-1370184045")

Please help. I couldn't figure out where the problem is.

**Comment by edward121** [comment]
When can you create the RealmStore module for Contenful-persistence?

**Comment by loudmouth** [comment]
Official support for Realm is not planned at the moment, but it may be something that I will attend to in several months time. However, since there is no official plan for adding support, I would not count on waiting for it. 

As neonichu mentions above, it should not be very difficult to implement, so if Realm support is an important requirement for you, I recommend looking into implementing yourself. I will also welcome pull requests for Realm support if contributing is somethat that interests you.
