### ISSUE TITLE
ContentfulBundleSync tool??

### ISSUE THREAD

**Issue by jgresham-incomm** [contentful/contentful-persistence.swift#36]
Comments in the SynchronizationManager+SeedDB.swift file make reference to a command line tool that should be used to generate seed files.  Where can one obtain this tool.

**Comment by loudmouth** [comment]
Hey @jgresham-incomm nice find ;-)

The tool you're looking for is [here](https://github.com/contentful/contentful-utilities.swift)

It is relatively new, so installation is a bit cumbersome, but it should work just fine. If the instructions are unclear, please open an issue there.

Thanks.
