### ISSUE TITLE
Seeding multilanguage database does not work properly

### ISSUE THREAD

**Issue by marcin-b-softnauts** [contentful/contentful-persistence.swift#37]
> contentful-persistence.swift version number: 0.7.0
> Xcode version number: 9.0.1 (9A1004)

Hello,

I try to seed database with data from [contentful-utilities.swift](https://github.com/contentful/contentful-utilities.swift). I have entites that are in multiple languages (I use `LocalizationScheme.all`). And it fails to save entities in database. When I open sqlite file it does not contain any of my custom entries. But it does contain SyncInfo entity with token.

Here's my seed code:

```
let persistenceModel = PersistenceModel(spaceType: CFSyncInfo.self, assetType: CFAsset.self, entryTypes: entryTypes)
client = Client(spaceId: spaceId, accessToken: accessToken)
syncManager = SynchronizationManager(client: client,
                                     localizationScheme: LocalizationScheme.all,
                                     persistenceStore: store,
                                     persistenceModel: persistenceModel)

do {
    try syncManager.seedDBFromJSONFiles(in: bundleDirectoryName, in: bundle)
} catch {
    print("Error: \(error)")
}
```

The problem is that when seeding client does not contain `localeCodes` and that's why for `LocalizationScheme.all` no entities are created. To make it work it is required to set `localeCodes` before seeding database:

```
// SynchronizationManager+SeedDB.swift
public func seedDBFromJSONFiles(in directory: String, in bundle: Bundle) throws {
// ...
Client.update(jsonDecoder, withLocalizationContextFrom: space)

// update localeCodes here
let localeCodes = space.locales.map { $0.code }
self.update(localeCodes: localeCodes)
```

When I use `sync()` from `SynchronizationManager` database is populated properly. It's because `SynchronizationManager` has proper `localeCodes` set before saving to database.

**Comment by loudmouth** [comment]
Will take a look at this later in the week when I'm free

**Comment by loudmouth** [comment]
@marcin-b-softnauts it looks like you are correct!

Thanks for suggesting the fix, I will integrate the additional lines of code you provided and add some test cases. Look out for a new version later today, and thanks for your patience.
