### ISSUE TITLE
Cannot convert return expression of type

### ISSUE THREAD

**Issue by tapwork** [contentful/contentful-persistence.swift#38]
I updated to 
`Contentful 0.10.2`
`ContentfulPersistenceSwift 0.7.0`

But when compiling I get the error in `SynchronizationManager.swift`
```
Cannot convert return expression of type '[(key: FieldName, value: String)]' (aka 'Array<(key: String, value: String)>') to return type '[FieldName : String]' (aka 'Dictionary<String, String>')
```

also deleted the entire Pods folder and cleaned the target, but issue remains

**Comment by loudmouth** [comment]
Hi @tapwork, very strange...I just fired up a new project with the following Podfile and was able to build successfully. The versions were locked to `Contentful 0.10.2` and `ContentfulPersistenceSwift 0.7.0` as well.

```ruby
#!/usr/bin/ruby

use_frameworks!
platform :ios, "8.0"

target 'TestPodInstall' do
  pod 'ContentfulPersistenceSwift', '~> 0.7.0'
end
```

I wonder if a deeper clean might help: I personally like to use a bundler managed cocoapods and add plugins to most projects including `gem cocoapods-deintegrate` and `gem cocoapods-clean`

You can run the following then to really clean all traces of your pods and reintegrate them

```bash
bundle exec pod deintegrate
bundle exec pod clean
bundle exec pod install
```

I've also attached the new project for convenience. I realize my comment may not be helpful, so my last addition to try is to use the `master` branch of `ContentfulPersistenceSwift` as it is using `Contentful 1.0.0-beta1`.

[TestPodInstall.zip](https://github.com/contentful/contentful-persistence.swift/files/1496267/TestPodInstall.zip)

**Comment by loudmouth** [comment]
Hi @tapwork , have you been able to get the project to build, either at HEAD on the master branch of contentful-persistence.swift or with version 0.7.0 after deintegrating and reinstalling cocoapods?

**Comment by tapwork** [comment]
@loudmouth sorry I didn't have enough time yet. will check this week

**Comment by tapwork** [comment]
Fixed it.  the issue was that I built all my Pods against Swift 3.2
And filter of a Dictionary didn't return a  Dictionary before Swift 4.
That was the reason.
