### ISSUE TITLE
Xcode is crashing when NOT assigning a value to localeCode

### ISSUE THREAD

**Issue by tapwork** [contentful/contentful-persistence.swift#41]
Hi,

I just had a weird issue after updating to the latest contentful SDKs:
I have a custom model where I forgot to set the ```localeCode``` (regarding to your Docs it should not be empty.)
Creating this model (without assign a string value to ```localeCode```) caused Xcode to crash.
After digging into the console.app I found out that something is wrong with that model and the property ```localeCode```.
Setting the property fixed the issue. 
Just to let you know. It was tough to find it.

**Comment by loudmouth** [comment]
Hey @tapwork :wave:

When you say you forgot to 'set' the `localeCode` did you mean 'declare' in your Swift code?

You shouldn't need to manually set the `localeCode` when using the contentful-persistence.swift library.

**Comment by tapwork** [comment]
I forgot to assign a value to ```localeCode```like you must do for ```id``` if you create the model yourself and not via the SDK`s fetch

**Comment by loudmouth** [comment]
Ahh, so this was a factory method or initializer that you wrote yourself to create a CoreData that is `Persistable`?

**Comment by tapwork** [comment]
correct

**Comment by loudmouth** [comment]
Ok, thanks for alerting me. I'll have to think about whether or having a non-optional core data property is too cumbersome. Feel free to share any opinions if you have them.
