### ISSUE TITLE
How to map a list of Short Text in CoreData? 

### ISSUE THREAD

**Issue by tapwork** [contentful/contentful-persistence.swift#45]
I have a list of Names (Short Text). What is the best approach to map them into my CoreData model?
![screen shot 2017-12-21 at 13 37 53](https://user-images.githubusercontent.com/397342/34256187-68905448-e654-11e7-9e24-72f6d93ea06e.png)

**Comment by loudmouth** [comment]
Hey @tapwork thanks for your patience. Today is my first day back from holidays and i'll be attending to this ticket. Stay tuned...

**Comment by loudmouth** [comment]
So I have done some learning myself and figured out how to configure a CoreData attribute on an entity to contain an array of strings. Three things must be done to serialize and deserialize the strings array:

1. Declare the property on your Swift NSManagedObject subclass as `Data`
```swift
@NSManaged var stringsArray: Data?
```

2. Ensure the corresponding attribute is present on the matching entity in your Xcode data model with the type 'Binary Data'

3. To access the data after a fetch to the database, you will need to use `NSKeyedUnarchiver` to deserialize the data and access elements of the array like so: 

```swift
if let linkedStringsData = fetchResults.first?.symbolsArray, let linkedStringsArray = NSKeyedUnarchiver.unarchiveObject(with: linkedStringsData) as? [String] {
  // linkedStringsArray should now be accessible
}
```

Let me know how that works out for you.

**Comment by tapwork** [comment]
Hi @loudmouth 
thanks for helping me! Yesterday we decided to use a real content model instead of just a String. This makes it cleaner and flexible. But thanks again. Hope you enjoyed your holidays.

**Comment by loudmouth** [comment]
Glad you got it sorted. Going to close this issue for now. Happy coding :-)
