### ISSUE TITLE
Memory leak on method fetchAll<T>

### ISSUE THREAD

**Issue by jefnazario** [contentful/contentful-persistence.swift#52]
Hi, 
I have seen on Instruments console a memory leak when method `fetchAll<T>` at the class `CoreDataStore.swift` is called. Unfortunately, I still don't know the exact cause, but I have found some people facing the same leak issue.

The code snippet where the memory leak occurs can be seen below:
```
    public func fetchAll<T>(type: Any.Type, predicate: NSPredicate) throws -> [T] {
        let request = try fetchRequest(for: type, predicate: predicate)
        return try context.fetch(request).flatMap { $0 as? T }   <--- memory leak here
    }
```

For some reason when we call `NSManagedObjectContext.fetch().flatMap()` all the same time, a huge bunch of memory is consumed by it, check this out:
<img width="1015" alt="screen shot 2018-03-22 at 17 40 55" src="https://user-images.githubusercontent.com/2067078/37848489-18272912-2eb3-11e8-800d-0d64ca4bfbb8.png">

Well, the simple and easy solution for that it's separates the `fetch()` call from the `flatMap()`call. The difference of memory allocation it's really considerable. See image below:
<img width="1033" alt="screen shot 2018-03-23 at 15 30 27" src="https://user-images.githubusercontent.com/2067078/37848701-d34bcbda-2eb3-11e8-967e-454e5cb91b5d.png">

That's it. I'm sending a PR to solve this issue.
Thanks for reading.

**Comment by wrumble** [comment]
Anyone know why this happened? Just curious :)
