### ISSUE TITLE
Missing relationships between entries

### ISSUE THREAD

**Issue by marcin-bo** [contentful/contentful-persistence.swift#58]
Hi,

We experience issues with missing relationships between entries. 

Our sync request has many pages and it takes around one minute to download and save all entries in our database. If user quits the app in the middle of synchronization we loose some relationships between entries. They are not recreated even after restarting the application and completing the data synchronization process. 

When I do not interrupt the data synchronization process and wait one minute to sync all data, the relationships appear in the database.

Probably the problem is with `resolveRelationships()` function: it stores those missing relationships in `relationshipsToResolve` property in memory and after quiting the app we loose the content of it. Is it possible?

I reported similar issue few months ago #47 (when seeding database).

Cheers!

**Comment by marcin-bo** [comment]
Saving `relationshipsToResolve` to a file and reading it before next sync process seems to fix the issue.

**Comment by loudmouth** [comment]
Hey @marcin-bo ,

You have correctly identified that at current, this library doesn't do any special handling for a sync that is interrupted by a termination of the app. I'm curious to see how you worked-around the issue as I'm sure others in the community could benefit from this fix. Are you willing to PR?

**Comment by marcin-bo** [comment]
Hi @loudmouth ,

I would like to discuss my workaround, because it was done when facing hard deadline and does not contain any unit tests.

At the end of `resolveRelationships()` func I call new function `persistRelationshipsToResolve()`.

```swift
public func resolveRelationships() {
    //...
    persistRelationshipsToResolve()
}

private func persistRelationshipsToResolve() {
        if !JSONSerialization.isValidJSONObject(relationshipsToResolve) {
            resolveRelationshipErrorHandler(relationshipsToResolve)
            return
        }
        
        guard let data = try? JSONSerialization.data(withJSONObject: relationshipsToResolve, options: []) else {
            return
        }
        try? data.write(to: relationshipsToResolvePersistURL, options: [])
}
```

It saves unresolved relationships to a file.

I've also created func that loads unresolved relationships (if there are any):

```swift
public func resolvePendingRelationships(completion: @escaping (() -> ())) {
        guard let relationships = getPersistedRelationshipsToResolve(), !relationships.isEmpty else {
            completion()
            return
        }
        
        persistentStore.performAndWait { [weak self] in
            self?.relationshipsToResolve = relationships
            self?.resolveRelationships()
            self?.save()
            completion()
        }
}
```

I call `resolvePendingRelationships` before each synchronization:
```swift
syncManager.resolvePendingRelationships(completion: {
    self.syncManager.sync() { _ in
       // completion
    }
})
```

Full code here:
https://github.com/marcin-bo/contentful-persistence.swift/blob/8fcf115d1da96df79cdef07c3b5e5760adf15381/Sources/ContentfulPersistence/SynchronizationManager.swift

We also experienced some issues when saving `relationshipsToResolve` to a file - `Invalid type in JSON write (_SwiftValue)`, sth was wrong with dictionary in `relationshipsToResolve`, don't know why it appeared, so we added a handler for incorrect values there (we log it to our backend to investigate it).

```swift
public class SynchronizationManager: PersistenceIntegration {
// ...
public var resolveRelationshipErrorHandler: ([String: [FieldName: Any]]) -> () = { data in }
// ...
```

What do you think?

**Comment by loudmouth** [comment]
Hey @marcin-bo thanks so much for posting the workaround you implemented. I'll start working ont this tomorrow.

**Comment by loudmouth** [comment]
Out of curiousity, did your solution additionally require you to have custom logic in your `applicationWillTerminate(_:)` to make a save to your `NSManagedObjectContext`?

**Comment by marcin-bo** [comment]
Hi, 

I haven't add any custom logic in `applicationWillTerminate(_:)`. That could be wrong because when user quits the app after saving the relationships and before saving context - that could lead to some data inconsistency (possibly during next sync library would try to resolve pending relationships between entries that were not saved and which does not exist). Not sure if this is a serious issue because sync request would probably continue from page that was interrupted by user

Regarding invalid types: yes, I also thought that `DeletedRelationship` could be the reason of invalid type issues.
