### ISSUE TITLE
One-to-many references not updated

### ISSUE THREAD

**Issue by Klaudas** [contentful/contentful-persistence.swift#65]
Hey,

We're having several major issues with syncing

1. Model A has linked multiple reference type sub-model B. We've recently added more content defined by model B and attached it to existing data held by A entry. Although changes are logged and visible inside Contentful panel, the client side seems to ignore it, even though updates were made more than a month ago. 

I've tried to initiate sync on both: empty and already existing databases.

2. Same data structure. I've added additional locale (no new data, just locale), filled all the missing pieces on existing entries and it seems that Assets (images) are not synced properly for newly added language, it doesn't affect other properties. 

Note: asset is not localized and is used for all locales. This issue only exists when trying to sync on non-empty Database.

**Comment by loudmouth** [comment]
Hi @Klaudas,

Regarding point number 1, let me restate in my own words to make sure I understand your issue:

- You have a content type `A` that has a one-to-many field that holds an array of type `B`
- You add more entries of type `B` and additionally, reference those entries in your one-to-many field on type `A`.

Is this correct? If so, can you clarify what you mean by, "the client side seems to ignore it"? 

Regarding the second issue, is it the same issue as described in [this Github issue comment](https://github.com/contentful/contentful-persistence.swift/issues/62#issuecomment-430635624)? If so, the answer is the same as it is there—it is unfortunately a limitation of the API.

> It turns out that that adding a new locale to a space will not cause subsequent sync calls to return "new" content for assets ("new" in this case refering to populating the asset for all locales on the space with fallback-locale logic reflected).
> 
> I think the best strategy would be either to do another initial sync; or you could write a script to update your assets in some manner.

**Comment by loudmouth** [comment]
Hey @Klaudas ,

I haven't been able to try reproducing this today since I've been busy. I will see what I can do tomorrow however. If this issue is urgent, then I suggest opening a support ticket at support.contentful.com where I can better guarantee faster response times.

**Comment by loudmouth** [comment]
A quick update: i have just been able to reproduce the issue, but I have not yet identified the root cause. It seems that linking new assets and publishing correctly resolves them in the CoreData database, but linking new entries does not.

**Comment by loudmouth** [comment]
A quick update: i have just been able to reproduce the issue, but I have not yet identified the root cause. It seems that linking new assets and publishing correctly resolves them in the CoreData database, but linking new entries does not.

**Comment by loudmouth** [comment]
@Klaudas actually, I must rescind my earlier comment...earlier today, I created a model to manually test, but what _I forgot_ to do when I created this model was add the relevant line for the one-to-many field to the `static func fieldMapping() -> [FieldName: String]` function.

After adding the relevant line, I have tested both incrementally adding a new reference to my one-to-many links array, and also doing an initial sync and I see all the expected content every time.

This library also has tests that assert that one-to-many links are properly stored in CoreData and that the references are resolved. Thus, after my investigation, I cannot confirm a bug report and must assume, for now, that there might be a configuration issue with your project.

If you need help troubleshooting your project, then I suggest opening a support request so we can take a look at your project and content together.

**Comment by loudmouth** [comment]
@Klaudas did you ever figure this out?

**Comment by matelo** [comment]
@Klaudas is this issue still relevant?

**Comment by jroehl** [comment]
Closed due to inactivity
