### ISSUE TITLE
Usin native @NSManaged Dates for fields are not supported (sys dates work though)

### ISSUE THREAD

**Issue by loudmouth** [contentful/contentful-persistence.swift#71]
While of course `sys.updatedAt` and `sys.createdAt` can successfully be stored on custom `NSManagedObject` classes for content types, if a date is the type of a field on a content type, this library has no way of storing it as a native `@NSManaged var dateField: Date?`

While this can be worked around using a `String` instead of a `Date` as the type, it is preferable to implement this feature on the library itself.

**Comment by M2Bas** [comment]
Hey @loudmouth any update on this? is it on the roadmap?

**Comment by loudmouth** [comment]
Hey there @M2Bas 

As of 2019, I no longer work for Contentful. I'm not sure but I believe @manmal is the new maintainer of this project?

good luck ;-)

**Comment by matelo** [comment]
will be handled in version 0.15.0, currently in PR
