### ISSUE TITLE
Property cannot be marked @NSManaged because its type cannot be represented in Objective-C

### ISSUE THREAD

**Issue by wrumble** [contentful/contentful-persistence.swift#79]
I get the following when trying to setup persisting to coredata: 
`Property cannot be marked @NSManaged because its type cannot be represented in Objective-C` 
on the following line:
 `@NSManaged var image: Asset?`

The image attribute type in the core data model is `Binary Data`

**Comment by wrumble** [comment]
Do you have a working example of an app using contentful with core data that I could reference?

**Comment by matelo** [comment]
you can take a look at https://github.com/contentful/contentful-utilities.swift. This is tool for exporting content from Contentful to CoreData (and to file). So you can see how the persistence is used
