### ISSUE TITLE
Use of unresolved identifier 'SyncInfo'

### ISSUE THREAD

**Issue by wrumble** [contentful/contentful-persistence.swift#80]
I don't understand what sync info should be in your documentation? does it represent a `Post`? And what is the `managedObjectContext` variable in your example readme.md? Do you have an example app i can reference?

Thanks :)

**Comment by matelo** [comment]
Hello, you can find example app in this repo: https://github.com/contentful/the-example-app.swift. `managedObjectContext ` property is probably NSManagedObjectContext, but can you be more specific what is needed? Same with `SyncInfo`, there is no such class/struct available in Contentful.swift
