### ISSUE TITLE
Persisting RichTextDocument 

### ISSUE THREAD

**Issue by robatum** [contentful/contentful-persistence.swift#89]
Syncing Entities containing a RichTextDocument attribute via CoreData Transformable does not work for me. Anyone has a trick up his sleeve to make this work?

**Comment by tomkowz** [comment]
@robatum Hey, sorry for late response!

The `RichTextDocument` is designed to be stored in the Core Data using `Transformable` type.

In order to do store `RichTextDocument` in Core Data you need to follow these steps:

1) Create a type for your Core Data entity and make sure the `fieldMapping` is set for the `RichTextDocument` field (`content` in my case).
```
import Contentful
import ContentfulPersistence
import CoreData

final class Article: NSManagedObject, EntryPersistable {
    static var contentTypeId: ContentTypeId = "article"

    @NSManaged var id: String
    @NSManaged var localeCode: String?
    @NSManaged var createdAt: Date?
    @NSManaged var updatedAt: Date?

    @NSManaged var title: String
    @NSManaged var content: RichTextDocument

    static func fieldMapping() -> [FieldName : String] {
        return [
            "title": "title",
            "content": "content"
        ]
    }
}
```

2) Create value transformer:
```
import Contentful
import Foundation

final class RichTextDocumentTransformer: ValueTransformer {
    override class func transformedValueClass() -> AnyClass {
        NSData.self
    }

    override func transformedValue(_ value: Any?) -> Any? {
        guard let text = value as? RichTextDocument else { return nil }

        return try! NSKeyedArchiver.archivedData(withRootObject: text, requiringSecureCoding: false)
    }

    override class func allowsReverseTransformation() -> Bool {
        true
    }

    override func reverseTransformedValue(_ value: Any?) -> Any? {
        guard let data = value as? Data else { return nil }
        return try! NSKeyedUnarchiver.unarchivedObject(ofClass: RichTextDocument.self, from: data)
    }
}
```

3) Add attribute with a type `Transformable` to Core Data entity and set:
- `Transformer`: `RichTextDocumentTransformer`
- `Custom Class`: `RichTextDocument`
- `Module`: `Current Product Module` - make sure this is set.

Let me know if that works for you.

**Comment by tomkowz** [comment]
No update in this thread. I am closing this for now.

**Comment by robatum** [comment]
Hey Tomasz, 

thank you very much for your reply and your excellent example!! I tried a similar approach based on NSSecureUnarchiveFromDataTransformer but couldn't make RichTextDocument conform to NSSecureCoding ;-) . 

Your approach is working for me but with one (important) limitation: As long as I only have Text Blocks and Paragraphs all is good but as soon as I'm embedding an Asset (Picture) or Embed to the Document the decoding fails. 

This is my DocumentTransformer right now: 

`
import Contentful
import Foundation

@objc(RichTextDocumentTransformer)
final class RichTextDocumentTransformer: ValueTransformer {
    override class func transformedValueClass() -> AnyClass {
        NSData.self
    }
override func transformedValue(_ value: Any?) -> Any? {
        guard let text = value as? RichTextDocument else { return nil }

        //let resultRender = DefaultArticleRenderer().render(document: text)
        do {
            let result = try NSKeyedArchiver.archivedData(withRootObject: text, requiringSecureCoding: false)
            return result
        } catch {
            Logger.error("Couldn't archive contentful data: \(error)")
            return nil
        }
    }

    override class func allowsReverseTransformation() -> Bool {
        true
    }

      override func reverseTransformedValue(_ value: Any?) -> Any? {
        guard let data = value as? Data else { return nil }
        do {
            guard let result = try NSKeyedUnarchiver.unarchiveTopLevelObjectWithData(data) as? RichTextDocument else {                    
                                             //NSKeyedUnarchiver.unarchivedObject(ofClass: RichTextDocument.self, from: data) else {
                Logger.error("Couldn't cast to RichTextDocument.")
                return nil
            }
            return result
        } catch {
            Logger.error("Couldn't unarchive contentful data: \(error)")
            return nil
        }   
    }
}

extension Contentful.RichTextDocument: NSSecureCoding {

    public static var supportsSecureCoding = false
    
} `



The error which I receive is:

> 🚨 Error ⏱ 06/25/2020 05:26:28:239 📂 RichTextDocumentTransformer.swift:41 : Couldn't cast to RichTextDocument.
valueNotFound(Swift.KeyedDecodingContainer<Contentful.Link.Sys.(unknown context at $104be348c).CodingKeys>, Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 2", intValue: 2), NodeContentCodingKeys(stringValue: "data", intValue: nil), JSONCodingKeys(stringValue: "target", intValue: nil), CodingKeys(stringValue: "sys", intValue: nil)], debugDescription: "Cannot get keyed decoding container -- found null value instead.", underlyingError: nil))

I also tried to run the demo project you've provided which gave me a different but related error, but this time already while encoding the document:

![Screenshot 2020-06-25 at 05 38 37](https://user-images.githubusercontent.com/600260/85651255-c8a0da80-b6a7-11ea-950f-3c89e02117e6.png)

I'm currently working with Xcode 11.5 on MacOS 10.15.4, I'm using these pods:
`
pod 'Contentful' , '5.0.11'
pod 'ContentfulPersistenceSwift' , '0.15.0'
`

Also tried the most recent version but without any differences. In case you have another idea, I'm open for recommandations :-).

Thx in advance! 

Best Andreas

**Comment by tomkowz** [comment]
Hey Andreas!

I noticed there is a typo in my example Core Data model. There should be `fileType` for Asset Model but is `filetype` instead.

Also sorry for the example not running as expected. I forgot that the space and the specific article are used as a base for another thing I am working right now so, indeed the project could crash.

Anyway, I think you're right that it seems impossible to persist more complex `RichTextDocument` at the moment. Link class seems to be the main limitation as I am check in the code. I'll open the issue on our internal tracker. Thanks!

**Comment by robatum** [comment]
Hey Tomasz,

thanks for your fast reply and taking the time to look into the issue! 

> I noticed there is a typo in my example Core Data model. There should be fileType for Asset Model but is filetype instead.

No worries that was a quick fix :-) 

> Anyway, I think you're right that it seems impossible to persist more complex RichTextDocument at the moment. Link class seems to be the main limitation as I am check in the code. I'll open the issue on our internal tracker. Thanks!

+1 Would be great to have this feature included as the persistence/syncing works flawless otherwise and we would prefer to use it over a custom implementation.

Have a great weekend! 

Best Andreas

**Comment by gKamelo** [comment]
Hey Tomek xD

+1 for Link support in `RichTextDocument` as that's the only puzzle that we need to have to fully support persistence;)

**Comment by pknuth** [comment]
+1

**Comment by SDC-KurtTreangen** [comment]
Hello @tomkowz, apologies if this is the wrong thread but just wanted to check if there is an update regarding...

> Anyway, I think you're right that it seems impossible to persist more complex RichTextDocument at the moment. Link class seems to be the main limitation as I am check in the code. I'll open the issue on our internal tracker. Thanks!

Our content team is currently trying to leverage `Link`s within within rich text so this would be greatly appreciated.

**Comment by mariuskatcontentful** [comment]
@SDC-KurtTreangen this should now be fixed if you could check and verify.

**Comment by SDC-KurtTreangen** [comment]
Hello @mariuskatcontentful ,

When attempting to test the fix that was included with https://github.com/contentful/contentful.swift/tree/5.5.1 I receive the following error when using CocoaPods.

```
[!] CocoaPods could not find compatible versions for pod "Contentful":
  In Podfile:
    Contentful (~> 5.5.1)

    ContentfulPersistenceSwift was resolved to 0.17.4, which depends on
      Contentful (~> 5.4.1)
```

**Comment by mariuskatcontentful** [comment]
@SDC-KurtTreangen Thanks for catching that. I sorted it if you want to check again.

**Comment by SDC-KurtTreangen** [comment]
Sorry for the late response @mariuskatcontentful . Everything is working as expected with the latest version. Thanks!

The solution on our end was to switch on the `Link`. If `entryDecodable`, cast it to our custom protocol for representing in line links, if `entry` or `unresolved` fetch the link from our local `CoreDataStore` by its `id`. This allows us to load rich text with in line links from CoreData and from the Client API.
