### ISSUE TITLE
I cannot synchroize my model 

### ISSUE THREAD

**Issue by edward121** [contentful/contentful-persistence.swift#9]
![screen shot 2017-03-05 at 07 03 33](https://cloud.githubusercontent.com/assets/22666011/23585020/a4a73ea0-0172-11e7-8fb3-7858ed6aee7d.png)
![screen shot 2017-03-05 at 07 03 51](https://cloud.githubusercontent.com/assets/22666011/23585021/a5194f5e-0172-11e7-9305-ec91839e186c.png)
![screen shot 2017-03-05 at 07 12 03](https://cloud.githubusercontent.com/assets/22666011/23585047/2c545fae-0173-11e7-8f08-deedab06920e.png)
First screen is core data model and second is content type model.
This makes a crash now such this.
How can I solve this problem?

**Comment by loudmouth** [comment]
Hi @edward121,

To use contentful-persistence, you need to make sure you call [map](https://github.com/contentful/contentful-persistence.swift/blob/master/Sources/ContentfulSynchronizer.swift#L66)

```
public func map(contentTypeId: String, to type: Resource.Type, propertyMapping: [String:String]? = nil)
```

To create a mapping from a field on a Contentful content type to an attribute on your CoreData data  model. 

As you can see in the photo you posted with your debug console, the `mapping` dictionary used to create a CoreData entry is empty in this case.

Your code should look something like the following:

```
self.synchronizer = ContentfulSynchronizer(client: self.client, persistenceStore: self.store)

self.synchronizer.mapAssets(to: Asset.self)
self.synchronizer.mapSpaces(to: SyncInfo.self)

// Replace With your Contentful content type id
self.synchronizer.map(contentTypeId: "CONTENTFUL_CONTENT_TYPE_ID", to: Record.self)
```

contentful-persistence will automatically infer the mapping dictionary, but for this to work, the field names on your content model must be the same as the property names on your CoreData Entity.
See the attached photo below to see a `mapping`  dictionary that is complete:

<img width="601" alt="screen shot 2017-03-06 at 09 45 14" src="https://cloud.githubusercontent.com/assets/4554909/23602704/fe42eb8c-0251-11e7-941c-f6998a9d8070.png">

**Comment by edward121** [comment]
Thanks for your support.
There's the problem in the entity model definition.
