### ISSUE TITLE
Coredata relationship not getting synced when un-publishing and publishing an entry with reference

### ISSUE THREAD

**Issue by pravking** [contentful/contentful-persistence.swift#94]
In the contetful portal, when i un-publish an entry which has reference to other entries and then republish it again, the reference between them are re-instated. However, when syncing this does not happen.

In the iOS DB when entry is unpublished, the relationship is nullified according to delete rule, however when the entry is republished the relationship is not getting synced.

For example - suppose we have an 'Article' entry which references another 'Category' entry. If i unpublish the 'category' entry it is getting synced to the local DB and the relationship between them is nullified, however when i republish the 'Category' entry again, the entry itself is synced but the relationship between 'article' entry and 'category' entry is lost (in contentful portal this relationship exists as before). It is not getting synced.

In case of Android it is working without issues and the relationship is also getting synced.

**Comment by tomkowz** [comment]
@pravking please make sure you reset sync token and do a full sync again to verify whether republishing works for you. Let me know if everything is okay.

**Comment by pravking** [comment]
Thanks @tomkowz. I’ll try and let you know.

So for apps in production also we have to do a full re-sync by resetting sync token for this fix in the sdk update to work right?

**Comment by tomkowz** [comment]
Yes, I'd suggest to reset sync token on the prod and perform full resync. Not ideal, I know, but I'd recommend that.
